runtime: nodejs
env: flex
env_variables:
  SQL_USER: root
  SQL_PASSWORD: root
  SQL_DATABASE: tracedb
  INSTANCE_CONNECTION_NAME: shehack-trace:us-central1:trace
beta_settings:
  cloud_sql_instances: shehack-trace:us-central1:trace
